version: '3.8'
services:
  redis-master:
    container_name: redis-master
    image: harbor.dev.21vianet.com/cmdb/redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 180 1 --loglevel warning --requirepass cc
    volumes: 
      - cache:/data
    networks:
      - default
volumes:
  cache:
    driver: local
networks:
  default:
    external:
      name: work-net-dev